import { runSemanticInventory } from "/home/user/headroom/lib/contract-model/compiler/semantic-accountability/inventory";
import { reconcileInventoryWithComposition } from "/home/user/headroom/lib/contract-model/compiler/semantic-accountability/reconciliation";
import { rollupAgreementSemanticStatus } from "/home/user/headroom/lib/contract-model/compiler/semantic-accountability/rollup";
import type { SourceContextResult } from "/home/user/headroom/lib/contract-model/compiler/semantic-accountability/types";
import type { StageCaller } from "/home/user/headroom/lib/contract-model/compiler/llm-caller";
const TEXT = "The Borrower shall not incur Indebtedness exceeding $10,000,000. The Borrower shall maintain a Leverage Ratio of not more than 4.00 to 1.00 as of the last day of each fiscal quarter. The cure period is 30 days.";
const ctx = (text: string): SourceContextResult => ({ state: "COMPLETE_LOCAL_SOURCE", regions: [{ regionId: "operative", kind: "OPERATIVE", documentId: "d", sourceNodeId: "n", sectionRef: "6.02", charStart: 0, charEnd: text.length, text, expandedFor: null, truncatedAtBudget: false, unitExtension: null }], unresolvedReferences: [], reasons: [], totalChars: text.length, budgetChars: 1e5 });
const item = (excerpt: string, prop: string) => ({ localRef: "r", semanticRole: "OTHER", proposition: prop, excerpt, regionId: "operative", quantitativeValues: [], referencedTerms: [], referencedSections: [], parentRef: null, relatedRefs: [], materiality: "CRITICAL", ambiguity: "NONE", ambiguityReason: null, operative: "OPERATIVE" });
const caller: StageCaller = { providerName:"s", model:"s", isSynthetic:false, async call<T>(): Promise<T> { return { items: [item(TEXT, "this section contains provisions")], overallNotes: [] } as unknown as T; }, lastTelemetry: () => null };
(async () => {
  const sc = ctx(TEXT);
  const inv = await runSemanticInventory({ candidateRef: "overbroad", documentId: "d", sourceContext: sc, caller });
  const id = inv.items[0]!.inventoryItemId;
  console.log("accepted item values:", inv.items[0]!.quantitativeValues.map(v=>`${v.kind}:${v.rawText}`).join(", "));
  const composition = { rules: [{ inventoryItemIds: [id], capacityExpression: { kind: "MONEY", amount: 10000000 }, conditions: [{ inventoryItemIds: [], description: "tested quarterly; cure period 30 days", expression: { kind: "RATIO", value: 4 } }], exceptions: [], dependsOn: [] }], definitions: [], sharedCapacities: [] } as any;
  const acc = reconcileInventoryWithComposition({ inventory: inv, composition, dispositions: [], sourceContextState: sc.state });
  const roll = rollupAgreementSemanticStatus([{ candidateRef: "overbroad", compileStatus: "COMPLETED", verifyStatus: "VERIFIED_NO_MATERIAL_GAP_FOUND", accountability: acc, operativeStateUncertain: false, unresolvedCrossReferences: 0 }]);
  console.log("status:", inv.inventoryStatus, "unacc:", inv.unaccountedSource.length, "vals:", inv.uninventoriedValues.length);
  console.log("dispositions:", acc.items.map(i=>i.disposition).join(","), "| complete:", acc.semanticallyComplete, "| rollup:", roll.status, "| reasons:", acc.reasons);
})();
