/**
 * PHASE 3 FINAL CLOSURE SYNTHESIS - zero-cost cumulative evidence gate. No model call, no production change.
 * Writes docs/phase-3-closure/01..11. Deterministic facts are read from the frozen artifacts; the legal/semantic
 * classifications are recorded as data with their reasoning and are the auditor's, not a model's.
 * Run: [VITEST_TARGETED_JSON=.. VITEST_FULL_JSON=.. VITEST_FULL_BASE_JSON=.. VITEST_FLAKE_JSON=.. TSC_LOG=.. LINT_LOG=.. BUILD_LOG=..] npx tsx scripts/phase-3-closure-synthesis.ts
 */
import { existsSync, readFileSync } from "node:fs";
import { writeJson } from "./f7b-lib";
import { readJson, sh, sha256 } from "./phase-3-601-revalidation-lib";

/* eslint-disable @typescript-eslint/no-explicit-any */
type Any = any;
const OUT = process.env.CLOSURE_OUT ?? "docs/phase-3-closure";
const at = () => new Date().toISOString();
const STARTING_SHA = process.env.CLOSURE_STARTING_SHA ?? "7c18b3eac834c85539e05b613b0a80b04da02c19";
const CLOSURE_BASELINE_SHA = "7c18b3eac834c85539e05b613b0a80b04da02c19";
const A = (n: string) => readJson<Any>(`docs/phase-3-final-601/${n}.json`);
const file = (env: string) => { const p = process.env[env]; return p && existsSync(p) ? readFileSync(p, "utf8") : null; };
const json = (env: string) => { const p = process.env[env]; return p && existsSync(p) ? readJson<Any>(p) : null; };

// ---------------- §1 freeze
const head = sh("git rev-parse HEAD");
const dirty = sh("git status --porcelain").split("\n").map((l) => l.trim()).filter(Boolean).filter((l) => !/docs\/phase-3-closure(-final)?\/|docs\/phase-3-entity-scope-final\/|scripts\/phase-3-closure-synthesis\.ts/.test(l));
let lsRemote: string | null = null; try { lsRemote = sh("git ls-remote origin refs/heads/claude/headroom-scaffold-covenant-engine-jrijk8").split(/\s+/)[0] || null; } catch { lsRemote = null; }
let tracking: string | null = null; try { tracking = sh("git rev-parse origin/claude/headroom-scaffold-covenant-engine-jrijk8") || null; } catch { tracking = null; }
const remote = lsRemote ?? tracking;
const trees = { "lib/": sh("git rev-parse HEAD:lib"), "lib/contract-model/compiler/": sh("git rev-parse HEAD:lib/contract-model/compiler"), "lib/contract-model/compiler/semantic/": sh("git rev-parse HEAD:lib/contract-model/compiler/semantic") };
const freeze = { startingSha: STARTING_SHA, head, headIsStarting: head === STARTING_SHA, workingTreeClean: dirty.length === 0, dirtyOutsideThisMission: dirty, remote: { url: sh("git remote get-url origin"), branch: "claude/headroom-scaffold-covenant-engine-jrijk8", sha: remote, source: lsRemote ? "git ls-remote" : "origin/ tracking ref (ls-remote returned nothing through the session proxy)" }, remoteAtHead: remote === head, productionTreeHashes: trees, closureBaselineSha: CLOSURE_BASELINE_SHA, libChangedSinceClosureBaseline: sh(`git diff --name-only ${CLOSURE_BASELINE_SHA} HEAD -- lib/`).split("\n").filter(Boolean), productionChangedByThisMission: sh("git diff --name-only HEAD -- lib/").trim().split("\n").filter(Boolean), paidCalls: 0, spendUsd: 0, phase4Started: false };
// ---------------- ENTITY-SCOPE GATE (the remediation of the closure blocker): read, and verified against the current production files
const ES_DIR = "docs/phase-3-entity-scope-final";
const ES = existsSync(`${ES_DIR}/08-entity-scope-gate.json`) ? readJson<Any>(`${ES_DIR}/08-entity-scope-gate.json`) : null;
const ESB = existsSync(`${ES_DIR}/05-blocker-replay.json`) ? readJson<Any>(`${ES_DIR}/05-blocker-replay.json`) : null;
const ESR = existsSync(`${ES_DIR}/04-frozen-ir-replay.json`) ? readJson<Any>(`${ES_DIR}/04-frozen-ir-replay.json`) : null;
const esHashesMatch = ES ? (ES.productionFiles as Any[]).every((f) => existsSync(f.path) && sha256(readFileSync(f.path)) === f.sha256) : false;
const esPassed = ES !== null && ESB !== null && ES.verdict === "ENTITY_SCOPE_GATE_PASSED" && esHashesMatch && ESB.verdict === "F0_NO_LONGER_A_CONFIDENTLY_WRONG_AUTHORITATIVE_CONCLUSION";
const esEvidence = ES ? `${ES_DIR}/08 ${ES.verdict} (${ES.summary.PASS}/${ES.summary.total}); production file hashes ${esHashesMatch ? "match" : "DO NOT match"} the current tree; 05 ${ESB?.verdict}; replay ${JSON.stringify(ESR?.statusCounts ?? {})}` : "no entity-scope gate artifact present";

// ---------------- frozen final-run facts (150-158)
const T153 = A("153-trust-gate"), P152 = A("152-pass-c"), S155 = A("155-reference-score"), V154 = A("154-verifier"), D151 = A("151-production-compile-and-delivery"), L150 = A("150-precision-revalidation-ledger"), G158 = A("158-final-revalidation-verdict");
const trust = (T153.hardTrustCounters as Any[]).map((t) => ({ counter: t.counter, value: t.value, state: t.state }));
const trustAllZeroMeasured = trust.every((t) => t.value === 0 && t.state === "MEASURED") && trust.length === 14;
const passC = P152.summary;
const compile = readJson<Any>("tests/fixtures/unseen-packages/phase-3-final-601-precision-revalidation/compile-result.json");
const rules: Any[] = compile.rules; const R = new Map<string, Any>(rules.map((r) => [r.ruleId, r]));
const inv = new Map<string, Any>(compile.frozenInventory.items.map((i: Any) => [i.inventoryItemId, i]));
const findings: Any[] = readJson<Any>("tests/fixtures/unseen-packages/phase-3-final-601-precision-revalidation/verify-result.json").findings;

// ---------------- 01 evidence registry (§3-§5)
const commit = (s: string) => { try { const [sha, date, subject] = sh(`git log -1 --format="%H|%cs|%s" ${s}`).split("|"); return { sha, date, subject }; } catch { return { sha: s, date: null, subject: "UNRESOLVED" }; } };
const tranche = (id: string, shas: string[], artifacts: string[], productionVersion: string, scope: string, proves: string[], doesNotProve: string[], status: string) => ({ id, commits: shas.map(commit), artifacts, productionVersionTested: productionVersion, scope, whatItProves: proves, whatItDoesNotProve: doesNotProve, evidenceStatus: status });
const registry = [
  tranche("SOURCE_ACCOUNTABILITY_CLOSURE", ["d5144d1cb2f4612132847cdb28a9547506bab469"], ["docs/source-coverage-repair/29-closure-audit.json (NOT_CLOSED at first audit)", "docs/source-coverage-repair/33-final-closure-audit.json", "docs/source-coverage-repair/35-final-final-closure-certification.json", "docs/source-coverage-repair/37-final-certification.json (finalVerdict SOURCE_COVERAGE_TRUST_BOUNDARY_CLOSED; 34 rows: 28 CLOSED, 6 REVIEW_ONLY, 0 BLOCKER; 0 dangerous silent completions)"], "structural index / coverage audit as of 2026-09-03 (pre-F1)", "deterministic source-coverage scanner + red-team reproduction harnesses over the frozen discovered failure universe", ["a discovered silent-completion route in source coverage is closed or review-only; no production-reachable latent blocker", "child-descent ownership and numbered-caption positive evidence are deterministic"], ["semantic quality of any compiled unit", "current Pass-A behaviour (Pass A v4/v5 came later)"], "DIRECTLY_APPLICABLE"),
  tranche("F1_TO_F6_POST_FIX", ["a9425587", "1a4070b", "01a69147", "02af0865", "5e171383", "9b4c10bf"], ["docs/phase-3-remediation-f1/ (compiler caller tool_use/tool_result protocol)", "docs/phase-3-remediation-f2/06-deterministic-relink-summary.json (clause hierarchy by context)", "docs/phase-3-remediation-f6/08-tests-and-results.json (F6_CLOSED: partial composites survive normalization)", "docs/phase-3-remediation-f5-3b-resume/09-final-summary.json (F5_CLOSED: E2 ensemble certified against E1)", "docs/phase-3-remediation-f3/04-final-summary.json (F3_CLOSED: scale-aware verifier normalization)", "docs/phase-3-remediation-f4/04-final-summary.json (F4_CLOSED: authenticated retrieved-source evidence)"], "compiler v3-era caller, structural index, Pass A v4/v5, verifier v2 (2026-09-03..10)", "each a root-caused defect with a generic fix and its own post-fix test/paid evidence", ["the caller obeys the tool protocol and keeps provisional submissions", "sub-clause nesting is inferred from context", "partial composites are preserved with UNSUPPORTED operands rather than dropped", "the dual-pass Pass-A ensemble is stable run-to-run (E1 vs E2 pre-registered scorer)", "the verifier normalizes scale and authenticates retrieved evidence"], ["current 6.01 semantic quality", "sharded execution (F-7 came later)"], "DIRECTLY_APPLICABLE"),
  tranche("F7_ARCHITECTURE_AND_CANARY", ["8b6bd445", "c58acd9", "d9949102", "1660817c", "aef7a00b", "9c97a544", "76e76a17", "c9b28224e118f6a5e54f99da88715da110ad7dee"], ["docs/phase-3-remediation-f7a/04-gate-evaluation-and-final-summary.json (F7A_READY_FOR_PAID_CANARY)", "docs/phase-3-remediation-f7b/12-final-gate.json (Stage 1: F7_NEEDS_ARCHITECTURAL_ITERATION - the 317-lineage-loss run)", "docs/phase-3-remediation-f7b1/ (rerun of the 5 Stage-1 shards, F7_NOT_SAFE)", "docs/phase-3-remediation-f7b2/09-final-gate.json (source-anchored definition attribution)", "docs/phase-3-remediation-f7b3b/09-closure-gate.json (definition-conflict variants preserved)", "docs/phase-3-remediation-f7b3c/14-wave-b-closure-gate.json", "docs/phase-3-remediation-f7b3d/18-regression.json (trust scorer unified)", "docs/phase-3-remediation-f7b3e/README.md + 06-per-shard-ledger.json (F7_CANARY_PASSED 25/25, 36/36 real shards, $13.90)"], "bounded shard architecture v1 on Section 1.01 (353,523 chars / 379 definitions); planner v1", "many-shard mechanics on the largest unit: attribution, conflict preservation, lineage/value retention, bounded contexts, sharded transport", ["36 real shards execute with every trust count zero", "definition attribution is source-anchored and conflicts are preserved as variants", "resume by shard hash never re-executes a terminal shard"], ["current final-production semantic recovery (its semantic percentages are canary-era, planner v1, and are NOT current metrics)", "the 6.01 unit"], "DIRECTLY_APPLICABLE (mechanics) / HISTORICAL_ROOT_CAUSE_ONLY (Stage-1 failure)"),
  tranche("F7C_PRODUCTION_ACTIVATION", ["2cfb6b3f8e8a99b6ff9010307726ffa8f7b6a2ac"], ["docs/phase-3-remediation-f7c/05-f7c-gate.json (28/28 F7_PRODUCTION_PATH_READY_FOR_FINAL_VALIDATION)", "docs/phase-3-remediation-f7c/02-certified-vs-activated-differential.json", "tests/contract-model/f7c-production-activation.test.ts"], "compile.ts with sharded execution wired into the public path", "the public compileCovenantToIR activates sharding exactly as the certified canary did", ["certified-vs-activated differential is empty", "execution mode selection is deterministic"], ["semantic quality"], "DIRECTLY_APPLICABLE"),
  tranche("F7C1_FROZEN_INVENTORY_TRUST_BOUNDARY", ["a474ab3ba42c2518b1dabe552b73dd37712c43e6"], ["docs/phase-3-remediation-f7c1/03-f7c1-gate.json (21/21)", "tests/contract-model/f7c1-frozen-inventory-resume.test.ts", "lib/contract-model/compiler/semantic/frozen-inventory-resume.ts"], "frozen-inventory resume validator", "a frozen Pass-A inventory can only be resumed against the identical source context", ["source-context-hash / re-anchoring identity is enforced before any resumed compile"], ["that any particular inventory is semantically complete"], "DIRECTLY_APPLICABLE"),
  tranche("WHOLE_AGREEMENT_COST_PREFLIGHT", ["a013ffdc4195257505a2e6546e984e7153cbf5bb"], ["docs/phase-3-final-chewy/14-phase-3-closure-gate.json (PHASE3_FINAL_COST_BOUND_BEFORE_START, 0 paid calls)", "docs/phase-3-final-chewy/README.md"], "whole-agreement planner over the full package", "structural reach, deterministic package parsing, semantic-unit planning, reference-set framing, cost scaling", ["the whole agreement can be parsed, routed and planned deterministically", "cost scales as the frozen methodology predicts"], ["ANY semantic validation of the whole agreement - the run never executed; the inability to afford it is not a Phase-3 failure"], "DIRECTLY_APPLICABLE (structural/cost) / NOT_SEMANTIC_EVIDENCE"),
  tranche("SECTION_601_VALIDATION_HISTORY", ["d51e7f275f6a7ffbaa2f61c19dd823b9da143b23", "f108ba24886e689830a3e3ddff421013e8f20d36", "8731f01", "f3b885b", "5bd15c2", "e6baf51", "51fda65", "f944790", "1b36eb64", "1fd23881", "80671aa8562d3aa0ac2c6bd3120f56cda6aa91aa", "6cc1c5de51a56d93bf9094714c3f1337169be71f", "7c18b3eac834c85539e05b613b0a80b04da02c19"], ["docs/phase-3-final-601/README.md (every tranche)", "11 cost-bound before start (0 calls)", "21 HD-1 voided run", "34 HD-2 stopped after a successful Pass A", "46 HD-3 banked inventory never persisted", "62 worker restart killed Pass A (HD-4 candidate)", "73-hd4-gate.json (durable replay certified, 0 cost)", "87-final-paid-verdict.json (NOT_SAFE 18/21: the 98-item shard lost lineage) + 88 (HD-5/HD-6)", "103-remediation-gate.json (20/20) + 99-101 (HD-5 scorer / HD-6 reader)", "117-revalidation-verdict.json (REMEDIATION_FAILED 18/24: required context dropped at the interpretive budget)", "132-dependency-delivery-gate.json (29/29)", "146-precision-audit-gate.json (20/20, certified against 80671aa)", "149-final-preflight-gate.json (17/18: cost-bound only)", "158-final-revalidation-verdict.json (PHASE3_601_FINAL_REVALIDATION_PASSED 21/21)"], "compiler prompt v3 -> v5, planner v1 -> v4, required-dependency model none -> v2, verifier v2 (unchanged)", "one real unit (Section 6.01, 33,623 chars, 326-item frozen inventory) taken from failure to a passing trust gate through root-caused remediation", ["the current production path compiles the unit with every trust counter zero, all shards complete, required context delivered", "each historical failure has a root cause and a post-fix observation on the same unit"], ["semantic quality beyond the 8-item reference slice and the verifier's findings", "generalization (that is proven by the synthetic/cross-corpus evidence, not by this unit)"], "CURRENT (150-158) / HISTORICAL_ROOT_CAUSE_ONLY (11-117)"),
  tranche("EARLIER_CLOSURE_ATTEMPTS_AND_UNSEEN_PACKAGES", [], ["docs/final-phase3-closure/20-final-verdict.json (SEMANTIC_HOLDOUT_GENERALIZATION_FAILED - dense Article I definitions not decomposed; led to F-5/F-7)", "docs/final-semantic-decomposition/22-final-verdict.json (SEMANTIC_DECOMPOSITION_NEEDS_ITERATION)", "docs/final-lightweight-unseen.md (LIGHTWEIGHT_UNSEEN_TRUST_BOUNDARY_FAILED - led to the source-coverage campaign)", "docs/phase-3f2-unseen-validation.md (PHASE_3F_2_ENVIRONMENT_BLOCKED after substantial real progress)", "docs/phase-3f-unseen-package-validation.md, docs/phase-3f1-*.md (unseen-package structural/foundation certification series)"], "pre-remediation production versions", "historical: the failures that motivated the remediation series; unseen-package structural evidence", ["the failure modes were real, surfaced and root-caused rather than hidden"], ["current semantic quality"], "HISTORICAL_ROOT_CAUSE_ONLY (semantic) / DIRECTLY_APPLICABLE (structural unseen-package evidence)"),
];
writeJson(`${OUT}/01-evidence-registry.json`, { artifact: "PHASE 3 CLOSURE §3 - immutable evidence registry", at: at(), startingSha: STARTING_SHA, rule: "tranches prove different things and are never aggregated; historical failures are root-cause evidence, not current results", tranches: registry, incomparableMetricsNotCombined: ["F-7B canary semantic percentages (planner v1, Section 1.01)", "the 51fda65 NOT_SAFE run counters (pre-remediation)", "the 1b36eb6 REMEDIATION_FAILED counters (planner v2)", "source-coverage scanner rows", "the 150-158 final run"] });

// ---------------- 04 the 9 CRITICAL missing-from-composition items (§9)
const missingItems = (compile.accountability.items as Any[]).filter((i) => i.disposition === "MISSING_FROM_COMPOSITION").map((i) => inv.get(i.inventoryItemId));
const cls9: Record<string, { cls: string; role: string; substanceElsewhere: string; explicitlyLimited: string; misled: string; work: string; reasoning: string }> = {
  "inv-item:d7c98f9e0feadf05d4c207ab": { cls: "C_ACCOUNTABILITY_MAPPING_ARTIFACT", role: "EXCEPTION lead-in of basket (4)(a)", substanceElsewhere: "ir-rule:d3ca9f2d (6.01(b)(4)(a), PARTIAL) carries the subject ('Indebtedness ... incurred by any Restricted Party, to finance the purchase, lease, expansion ...') in its provenance excerpt and first condition; the lead-in item has no lineage only because the rule's inventoryItemIds are empty and Pass C found no deterministic correspondence for the lead-in wording", explicitlyLimited: "yes - Pass C MISSING (CRITICAL), unit semanticallyComplete=false", misled: "no - the (4)(a) permission is present with its cap formula and conditions", work: "PHASE3_ACCOUNTABILITY (lineage credit), no semantic work", reasoning: "decomposition-accounting mismatch: the model composed the basket as one rule and did not cite the lead-in item id" },
  "inv-item:52cb99788593930951c703bc": { cls: "C_ACCOUNTABILITY_MAPPING_ARTIFACT", role: "EXCEPTION lead-in of basket (13) (Refinancing Indebtedness)", substanceElsewhere: "ir-rule:40a36af7 (6.01(b)(13), PARTIAL) represents the refinancing permission with its capacity (principal + costs), its three provisos as conditions, 4 exceptions and 7 resolved dependencies", explicitlyLimited: "yes - Pass C MISSING (CRITICAL) plus the rule's own PARTIAL reasons", misled: "no", work: "PHASE3_ACCOUNTABILITY (lineage credit)", reasoning: "same accounting mismatch: no inventoryItemIds on the rule" },
  "inv-item:4ca43ad2a68a91809ea43063": { cls: "D_DUPLICATE_ALREADY_REPRESENTED", role: "CONDITION ('subject to the provisos that follow') of (13)", substanceElsewhere: "the provisos are conditions[0..2] of ir-rule:40a36af7", explicitlyLimited: "yes - Pass C MISSING", misled: "no", work: "none (connective item)", reasoning: "a connective inventory item whose semantic effect is already carried by the proviso conditions" },
  "inv-item:8cb1b19c9314d7698525a9d7": { cls: "A_TRUE_PHASE3_SEMANTIC_OMISSION", role: "ALTERNATIVE - branch (x) of (14): debt of a Restricted Party incurred to finance an acquisition or Investment", substanceElsewhere: "present ONLY in the provenance excerpt of ir-rule:e0669a81 ('(14) Indebtedness ... of (x) a Restricted Party incurred or issued to finance an acquisition or Investment or (y) Persons that are acquired ...'); NOT a structured condition on any of the four (14) rules, whose structured semantics are ratio gates over an UNLIMITED capacity", explicitlyLimited: "bounded: Pass C lists it MISSING (CRITICAL), the unit is REVIEW_REQUIRED and semanticallyComplete=false; the rule itself is marked COMPLETE", misled: "possible in the permissive direction if a consumer reads only structured fields: the acquisition nexus that qualifies the debt is absent from conditions", work: "PHASE3_SEMANTIC (a structured subject/nexus condition on the (14) rules)", reasoning: "the basket's qualifying subject matter is a legal limitation, not arithmetic" },
  "inv-item:0ff09e163857682f3d53b4d8": { cls: "A_TRUE_PHASE3_SEMANTIC_OMISSION", role: "ALTERNATIVE - branch (x) restated", substanceElsewhere: "as above (same span)", explicitlyLimited: "bounded (Pass C)", misled: "as above", work: "PHASE3_SEMANTIC", reasoning: "duplicate span of the (x) branch; classified with it" },
  "inv-item:6e4f0a6b9b35bacff18b03b6": { cls: "A_TRUE_PHASE3_SEMANTIC_OMISSION", role: "ALTERNATIVE - branch (y) of (14): debt of Persons acquired by / merged into a Restricted Party", substanceElsewhere: "provenance excerpt only; clause (d) (ir-rule:0de04497, Acquired Indebtedness) covers part of the (y) case but the (y) subject is not a structured condition of the (14) family", explicitlyLimited: "bounded (Pass C)", misled: "as above", work: "PHASE3_SEMANTIC", reasoning: "as (x)" },
  "inv-item:a889590458d5dcd2d4b1b09b": { cls: "A_TRUE_PHASE3_SEMANTIC_OMISSION", role: "ALTERNATIVE - branch (y) lead-in restated", substanceElsewhere: "as above", explicitlyLimited: "bounded (Pass C)", misled: "as above", work: "PHASE3_SEMANTIC", reasoning: "duplicate span of the (y) branch" },
  "inv-item:33551ba7940f9a29b5c616c4": { cls: "A_TRUE_PHASE3_SEMANTIC_OMISSION", role: "PERMISSION - (y) also covers consolidation with a Restricted Party, including designating an Unrestricted Subsidiary as Restricted", substanceElsewhere: "provenance excerpt only", explicitlyLimited: "bounded (Pass C)", misled: "as above", work: "PHASE3_SEMANTIC", reasoning: "part of the (y) subject" },
  "inv-item:8d8fe5e7934c15cc4066aed7": { cls: "D_DUPLICATE_ALREADY_REPRESENTED", role: "CONDITION ('subject to the provisos that follow') of (14)", substanceElsewhere: "the provisos (a)-(e) are the gates/rules ir-rule:e0669a81, c0feca0b, 0de04497, 12020258", explicitlyLimited: "yes - Pass C MISSING", misled: "no", work: "none (connective item)", reasoning: "connective item" },
};
const rows9 = missingItems.map((m: Any) => ({ inventoryItemId: m.inventoryItemId, sourceCitation: m.sourceSpan.sourceCitation, span: [m.sourceSpan.charStart, m.sourceSpan.charEnd], proposition: m.proposition, materiality: m.materiality, semanticRole: m.semanticRole, whyPassCMissing: "no lineage, no explicit disposition, and no deterministic correspondence in the composed IR (Pass C reason)", ...(cls9[m.inventoryItemId as string] as { cls: string; role: string; substanceElsewhere: string; explicitlyLimited: string; misled: string; work: string; reasoning: string }) }));
const counts9 = rows9.reduce((a: Record<string, number>, r) => { a[r.cls] = (a[r.cls] ?? 0) + 1; return a; }, {});
const trueOmissions = rows9.filter((r) => r.cls.startsWith("A_"));
writeJson(`${OUT}/04-final-601-critical-missing-audit.json`, { artifact: "PHASE 3 CLOSURE §9 - the 9 CRITICAL items Pass C reports MISSING_FROM_COMPOSITION, examined one by one", at: at(), source: "tests/fixtures/unseen-packages/phase-3-final-601-precision-revalidation/compile-result.json (frozen) + docs/phase-3-final-601/152-pass-c.json", rows: rows9, counts: counts9, trueOmissions: trueOmissions.map((r) => r.inventoryItemId), trueOmissionsAreBounded: true, boundedBy: "Pass C enumerates every one as MISSING (CRITICAL) with the item proposition; the unit is REVIEW_REQUIRED and semanticallyComplete=false; the (x)/(y) subject text is carried verbatim in the (14) rule's provenance excerpt. None is silent or unbounded.", unboundedTrueOmissions: 0, clusters: { "(4)(a) lead-in": ["inv-item:d7c98f9e0feadf05d4c207ab"], "(13) lead-in + proviso connective": ["inv-item:52cb99788593930951c703bc", "inv-item:4ca43ad2a68a91809ea43063"], "(14) (x)/(y) qualifying subject + proviso connective": ["inv-item:8cb1b19c9314d7698525a9d7", "inv-item:0ff09e163857682f3d53b4d8", "inv-item:6e4f0a6b9b35bacff18b03b6", "inv-item:a889590458d5dcd2d4b1b09b", "inv-item:33551ba7940f9a29b5c616c4", "inv-item:8d8fe5e7934c15cc4066aed7"] }, structuralObservation: "63 rules, 42 carry inventoryItemIds, 0 carry a description; the (4)(a), (13) and all four (14) rules carry no inventoryItemIds, so lineage for their lead-in items depends entirely on Pass C's deterministic correspondence" });

// ---------------- 05 the 6 verifier findings (§10-§14)
const prohib = ["ir-rule:170e314ceb35e54072b7ddba", "ir-rule:49f22aee601dde5b8b8162d5", "ir-rule:31ef4cb0be0026182f97f8ea"].map((id) => R.get(id));
const ratioPerms = ["ir-rule:01c9a005fd9c7649ddc26012", "ir-rule:6d2acc86b7f3dede7305f5df", "ir-rule:b21ac832418c33bcf91d0625"].map((id) => R.get(id));
const scopeFacts = { prohibitionRules: prohib.map((r) => ({ ruleId: r.ruleId, entityScope: r.entityScope, sufficiency: r.sufficiency, sufficiencyReasonsMentionScope: (r.sufficiencyReasons ?? []).some((s: string) => /scope|subsidiar/i.test(s)), provenanceExcerptBindsRestrictedSubsidiaries: /shall not permit any of their Restricted Subsidiaries/.test(String(r.provenance?.excerpt ?? "")), conditionsMentionSubsidiaries: JSON.stringify(r.conditions ?? []).match(/subsidiar/i) !== null })), permittedRatioDebtRules: ratioPerms.map((r) => ({ ruleId: r.ruleId, entityScope: r.entityScope, sufficiency: r.sufficiency, sufficiencyReasonsMentionScope: (r.sufficiencyReasons ?? []).some((s: string) => /scope|subsidiar/i.test(s)) })), scopeCensus: rules.reduce((m: Record<string, number>, r) => { const k = JSON.stringify(r.entityScope ?? []); m[k] = (m[k] ?? 0) + 1; return m; }, {}), rawWirePersisted: false, normalizerBehaviour: "normalize.ts matchEnum(): an entity tag the model emits that is not an EntityClassTag is dropped with no warning and no sufficiency change (lines 549-550); whether the model emitted only BORROWER or emitted an unrecognized restricted-subsidiary tag that was dropped cannot be told from the frozen evidence (raw wire output is not persisted)", noDeterministicScopeCrossCheck: "the provenance excerpt of the prohibition rules literally reads 'the Borrowers shall not, and shall not permit any of their Restricted Subsidiaries to ...' and no deterministic layer compares emitted entityScope against that text" };
const b14 = ["ir-rule:e0669a810b36ddf5bff018b3", "ir-rule:c0feca0b818c734f33a23962", "ir-rule:0de044975c1ddc20616dbf84", "ir-rule:12020258cf54c8d04bde5454"].map((id) => R.get(id)).map((r) => ({ ruleId: r.ruleId, section: r.sourceSectionRef, sufficiency: r.sufficiency, gate: r.capacityExpression?.gatedBy ? `${r.capacityExpression.gatedBy.kind}(${(r.capacityExpression.gatedBy.operands ?? []).map((o: Any) => o.kind).join(",")})` : "none", dependsOn: (r.dependsOn ?? []).map((d: Any) => `${d.relationshipType}->${String(d.targetRuleId).slice(8, 16)}`), unresolved: (r.unresolvedDependencies ?? []).map((u: Any) => `${u.relationshipType}->${u.targetRef}`) }));
const r4a = R.get("ir-rule:d3ca9f2def3509883e8a359b");
const ratioFacts = { ruleId: r4a.ruleId, sufficiency: r4a.sufficiency, reasonsNamingTheRatioDerivation: (r4a.sufficiencyReasons ?? []).filter((s: string) => /First Lien Leverage Ratio|MULTIPLY|UNSUPPORTED/i.test(s)).map((s: string) => s.slice(0, 200)), ratio25PresentInIr: /2\.5\b/.test(JSON.stringify(r4a)), whereItAppears: "inside the UNSUPPORTED node's attemptedStructure (RATIO 2.5 against Consolidated EBITDA) of the SUM's second operand; the source phrase is quoted in the rule's provenance", typedRatioNode: false };
const reclass = R.get("ir-rule:c6204d2aa73929fbafd3ae0f");
const reclassFacts = { ruleId: reclass.ruleId, sufficiency: reclass.sufficiency, conditions: (reclass.conditions ?? []).map((c: Any) => String(c.description).slice(0, 160)), reclassifiableToEdge: false, rightRepresentedInSubstance: true };
const findingAudit = [
  { ordinal: 0, findingType: findings[0].findingType, severity: findings[0].severity, classification: esPassed ? "E_RESOLVED_BY_DETERMINISTIC_GUARD (was A_PHASE3_CLOSURE_BLOCKER at the closure baseline)" : "A_PHASE3_CLOSURE_BLOCKER", postGuard: ESB ? { verdict: ESB.verdict, rows: ESB.rows.map((r: Any) => ({ ruleId: r.ruleId, before: r.before, after: r.after, endState: r.endState })), closureTest: ESB.closureTest } : null, disposition: "the top-level 6.01(a) prohibition rules carry entityScope [\"BORROWER\"] while their own provenance excerpt binds 'the Borrowers ... and ... any of their Restricted Subsidiaries'; the Permitted Ratio Debt permissions carry [\"BORROWER\"] while the source lets 'any of their Restricted Subsidiaries' incur. entityScope is an authoritative field (the real EntityClassTag enum, IR types.ts). A consumer reading it would conclude the prohibition binds only the Borrower (permissive-direction error) and that a Restricted Subsidiary cannot rely on the ratio permission (restrictive-direction error). The prohibition rules are PARTIAL and two ratio rules are COMPLETE, but no sufficiency reason, condition or limitation mentions scope, so the partiality does not prevent reliance on the wrong scope. Not explicitly limited anywhere (§11: not inferable from the top-level REVIEW_REQUIRED). The frozen run had entityScope empty everywhere (unspecified); the v5 prompt + fallback made the field populated and this run populated it under-inclusively.", facts: scopeFacts, rootCauseClass: "SEMANTIC_MODEL_DEFECT (model fill) compounded by a DETERMINISTIC PRODUCTION GAP: unrecognized entity tags are dropped silently and emitted scope is never cross-checked against the rule's own source text", blocking: !esPassed },
  { ordinal: 1, findingType: findings[1].findingType, severity: findings[1].severity, classification: "F_REVIEW_REQUIRED_BUT_BOUNDED", disposition: "frozen source (region offset 16856): 'provided that: (a) ...; (b) ...; (c) (X) ... or (Y) ...; or (d) such Indebtedness constitutes Acquired Indebtedness ...; (e) solely to the extent not permitted to be incurred in reliance on clauses (a) through (d) above ...'. The list is joined by semicolons with a single 'or' before (d) and (e) is a residual over '(a) through (d)': the ordinary drafting reading is DISJUNCTIVE - any one of (a), (b), (c) or (d) qualifies the acquisition debt. The verifier's cumulative reading ((a) AND (b) AND ((c) OR (d))) is not supported by the punctuation and would make Acquired Indebtedness (d) subject to three ratio tests, which the residual (e) drafting contradicts. Under the disjunctive reading the IR's (c)/(d)/(e) structure is faithful, but the IR fuses (a) and (b) into ONE rule gated by AND(OR(a-tests), OR(b-tests)) - an OVER-RESTRICTIVE grouping (it denies debt that satisfies only (a) or only (b)). That is a representation inaccuracy in the conservative direction: it cannot lead a consumer to believe something is permitted that the source prohibits. The (14) family is also flagged by Pass C (its (x)/(y) subject items are MISSING) so the unit is REVIEW_REQUIRED. Recorded as a bounded, conservative grouping error; the interpretive disagreement is disclosed.", facts: { rules: b14, sourceExcerpt: compile.sourceContext.regions[0].text.slice(16856, 16856 + 900).replace(/\s+/g, " ") }, rootCauseClass: "SEMANTIC_MODEL (grouping) + interpretive ambiguity", blocking: false },
  { ordinal: 2, findingType: findings[2].findingType, severity: findings[2].severity, classification: "C_PHASE4_EXECUTABILITY_CONCERN", disposition: "the 2.50:1.00 First Lien Leverage Ratio dependency of basket (4)(a)(ii) IS preserved: the rule is PARTIAL with reasons naming the algebraic derivation and the MULTIPLY type-check failure, the ratio value 2.5 and the metric sit in the UNSUPPORTED node's attemptedStructure, and the source phrase is in provenance. What is missing is a typed RATIO/formula node the arithmetic runtime could execute ('maximum principal amount such that FLLR <= 2.50:1.00' is a solve-for-x, not a literal). Semantic representation: present and explicit (PARTIAL). Execution: not yet expressible - Phase 4. The verifier's worry that a consumer might treat the UNSUPPORTED operand as zero is a consumer-contract concern for Phase 4 (an UNSUPPORTED operand must be treated as non-computable, never zero).", facts: ratioFacts, rootCauseClass: "IR_SHAPE / PHASE4", blocking: false },
  { ordinal: 3, findingType: findings[3].findingType, severity: findings[3].severity, classification: "D_NON_MATERIAL_IR_SHAPE", disposition: "the legal right to allocate, classify and reclassify is represented in substance on ir-rule:c6204d2a (conditions carry the right, the one-category rule and the (X)/(Y) Effective-Date deeming provisos; sufficiency AMBIGUOUS because the (X)/(Y) section references are structurally ambiguous). No normalized RECLASSIFIABLE_TO edge exists. Phase 4 can normalize the edge from this rule without reinterpreting the source.", facts: reclassFacts, rootCauseClass: "IR_SHAPE", blocking: false },
  { ordinal: 4, findingType: findings[4].findingType, severity: findings[4].severity, classification: "C_PHASE4_EXECUTABILITY_CONCERN (verifier deterministic check is over-strict about WHERE the value may live)", disposition: "deterministic MISSING_RULE: 'RATIO 2.5 does not appear as a RATIO value anywhere in the IR'. It appears inside the UNSUPPORTED operand's attemptedStructure and in provenance; the check only scans typed RATIO nodes. Same boundary as finding 2: threshold present and explicit, typed execution absent (Phase 4). Recurred with an identical finding id in both paid runs, so it is stable, not variance.", facts: ratioFacts, rootCauseClass: "IR_SHAPE / PHASE4 + verifier over-strictness", blocking: false },
  { ordinal: 5, findingType: findings[5].findingType, severity: findings[5].severity, classification: "D_NON_MATERIAL_IR_SHAPE", disposition: "deterministic MISSING_RECLASSIFICATION: no RECLASSIFIABLE_TO edge. Same substance as finding 3; already downgraded NON_MATERIAL by the Layer-2 reviewer. Recurred with an identical id in both runs.", facts: reclassFacts, rootCauseClass: "IR_SHAPE", blocking: false },
];
writeJson(`${OUT}/05-final-verifier-findings-audit.json`, { artifact: "PHASE 3 CLOSURE §10-§14 - the 6 current verifier findings examined against frozen source and frozen IR", at: at(), source: "tests/fixtures/unseen-packages/phase-3-final-601-precision-revalidation/verify-result.json (frozen)", findings: findingAudit, closureBlockingFindings: findingAudit.filter((f) => f.blocking).map((f) => `F${f.ordinal} ${f.findingType}`), entityScopeClosureTest: { consumerWouldBelieveBorrowerOnly: true, authoritativeRuleMarkedComplete: ratioPerms.filter((r) => r.sufficiency === "COMPLETE").map((r) => r.ruleId), prohibitionRulesPartialForUnrelatedReasons: prohib.map((r) => r.ruleId), explicitScopeLimitationAnywhere: false, verdict: "POTENTIAL_PHASE3_BLOCKER -> BLOCKER (no explicit partial/review state prevents unsafe reliance on the scope field)", note: "facts of the FROZEN IR before the guard", postGuard: ESB ? { closureTest: ESB.closureTest, verdict: ESB.verdict } : null, resolved: esPassed }, cumulativeProvisoTest: { verifierReading: "cumulative (a) AND (b) AND ((c) OR (d))", auditorReading: "disjunctive (a) OR (b) OR (c) OR (d), with (e) residual", irStructure: "(a)AND(b) as one rule; (c), (d) independent alternatives; (e) residual LIMITED_BY (c)/(d)", irAffirmativelyGrantsWhatSourceDoesNot: false, irOverRestricts: "yes - the fused (a)AND(b) rule", verdict: "NOT a closure blocker; bounded conservative grouping error, disclosed" }, ratioBoundary: { semanticRepresentation: "PRESENT (PARTIAL rule, provenance, attemptedStructure with 2.5 and the metric)", execution: "ABSENT (no typed solve-for-x node) - Phase 4", verdict: "PHASE_4_CONCERN" }, reclassificationBoundary: { legalRightRepresented: true, normalizedEdge: false, verdict: "IR_SHAPE_LIMITATION - Phase 4 may normalize" } });

// ---------------- 03 defect closure ledger (§19)
const ledger = [
  { defect: "F-1 compiler caller tool-protocol defect", rootCause: "caller dropped tool_result pairing and provisional submissions", fixSha: "a942558715b206757d1e518638969e1b760efbc9", postFixEvidence: "docs/phase-3-remediation-f1/05-test-and-regression-results.json; every paid run since (F-7B..158) ran the protocol without a caller failure (0 provider/schema failures in 150-158)", currentRisk: "none observed", closed: true },
  { defect: "F-2 structural sub-clause mis-nesting", rootCause: "structural level inferred from label shape alone", fixSha: "1a4070b020249157ab705dbb4244bb755072bd5f", postFixEvidence: "docs/phase-3-remediation-f2/06-deterministic-relink-summary.json; 6.01's 31 (b)(n) clauses partitioned and owned exactly once in every plan since (127, 144, 151)", currentRisk: "one ambiguous reference (6.01(b)(1)(Z)) preserved as AMBIGUOUS, never guessed", closed: true },
  { defect: "F-3 verifier scale-unaware quantitative normalization", rootCause: "verifier compared unscaled numbers", fixSha: "5e171383e1ec6e9505ea6812fd3d3ddf0768c696", postFixEvidence: "docs/phase-3-remediation-f3/04-final-summary.json (F3_CLOSED); 155: 0 reference contradictions over 50 quantitative values", currentRisk: "none", closed: true },
  { defect: "F-4 verifier unauthenticated retrieved evidence", rootCause: "verifier trusted IR-cited retrievals", fixSha: "9b4c10bf7844f2966cb4c19dac90ee5fe6d9a7c5", postFixEvidence: "docs/phase-3-remediation-f4/04-final-summary.json (F4_CLOSED); 153 source-unverifiable authoritative IR = 0", currentRisk: "none", closed: true },
  { defect: "F-5 Pass-A discovery instability on dense definitions (original 6.08 problems)", rootCause: "single-pass inventory over ad-hoc slots; dense multi-clause definitions not decomposed", fixSha: "02af0865b094757814c354fb7c184bac3add4b1f (F-5.3B E2 certification; series F-5 .. F-5.3B)", postFixEvidence: "docs/phase-3-remediation-f5-3b-resume/09-final-summary.json (F5_CLOSED, E1 vs E2 pre-registered); the frozen 326-item 6.01 ensemble (252 corroborated, 0 conflicted) resumed and compiled in 150-158", currentRisk: "INVENTORY_COVERAGE_GAP carried honestly: 17 unaccounted stretches (max 142 chars), 2 uninventoried $1.00 tokens, 72 single-run material items", closed: true },
  { defect: "F-6 IR type-check degradation (partial composites dropped)", rootCause: "normalizer discarded composites with an unsupported operand", fixSha: "01a69147629e720fba51ef8c743e62fc52c7e257", postFixEvidence: "docs/phase-3-remediation-f6/08-tests-and-results.json (F6_CLOSED); 150-158 IR keeps SUM/SUBTRACT structure with 6 explicit UNSUPPORTED operands (finding 2)", currentRisk: "typed execution of solve-for-x operands is Phase 4", closed: true },
  { defect: "F-7 large-unit compiler window / cost concentration (317-lineage-loss Stage-1 run)", rootCause: "one conversation per discovered section; planner v1 lost lineage across shards", fixSha: "8b6bd445 (F-7A) .. c9b28224 (F-7B.3E), 2cfb6b3f (F-7C)", postFixEvidence: "F-7B.3E 36/36 shards, 25/25 trust; F-7C 28/28; 153: distinct owned lineage lost 0, unresolved owned items 0", currentRisk: "none on the 6.01 unit; Section 1.01 canary-era semantic percentages are not current metrics", closed: true },
  { defect: "HD-1 in-run cost guard stricter than the frozen estimator", rootCause: "guard added a per-shard term the methodology does not price", fixSha: "f108ba24886e689830a3e3ddff421013e8f20d36 (disclosed) / 8731f01 (single guard implementation)", postFixEvidence: "docs/phase-3-final-601/21, 24; every later run's guard reproduces the frozen estimate to the cent (108, 148, 150: $12.153745)", currentRisk: "none", closed: true },
  { defect: "HD-2 Pass-A gate stricter than its specification", rootCause: "gate demanded INVENTORY_OK; INVENTORY_COVERAGE_GAP is a successful Pass A", fixSha: "f3b885b12f5bc91fcf886b7b3f77e84ed26661c3 (predicate exported and certified 6/6)", postFixEvidence: "docs/phase-3-final-601/46; the frozen inventory carries INVENTORY_COVERAGE_GAP and resumed through the gate in 104-117 and 150-158", currentRisk: "none", closed: true },
  { defect: "HD-3 expensive evidence persisted after an abortable gate (banked inventory lost)", rootCause: "frozen-inventory.json written only inside the post-compile block", fixSha: "f3b885b12f5bc91fcf886b7b3f77e84ed26661c3", postFixEvidence: "docs/phase-3-final-601/46; HD-4 durable persistence supersedes it (73); the 326-item inventory persisted at 51fda65 and resumed twice", currentRisk: "none", closed: true },
  { defect: "HD-4 paid Pass-A calls not durable until the pass returned (worker restart destroyed 11 calls)", rootCause: "no per-call durable record", fixSha: "e6baf51b6a1211323a2926daaba21ed4a3facd1c", postFixEvidence: "docs/phase-3-final-601/73-hd4-gate.json; tests phase-3-601-hd4-durable-replay / hd4-sigkill; 150: 7 durable shard records, 1 launch, 0 replays needed", currentRisk: "none", closed: true },
  { defect: "HD-5 scorer percent/scale normalization", rootCause: "numbersIn parsed 50% as 50 vs Pass A's 0.5; span cut before 'million'", fixSha: "f944790423c9a6f7046f46654ad1348611083204 (99/101 corrected scorer)", postFixEvidence: "114 and 155 scored with the corrected module: 0 incorrect, B6 REFERENCE_SET_ERROR recorded with original span", currentRisk: "none", closed: true },
  { defect: "HD-6 finalizer read-shape (contextualEmissions list vs count)", rootCause: "finalizer expected a list; production exposes a count", fixSha: "f944790423c9a6f7046f46654ad1348611083204 (100: canonical reader, NOT_MEASURABLE never 0)", postFixEvidence: "112 and 153 through scripts/phase-3-601-trust-read.ts: 14/14 MEASURED", currentRisk: "none", closed: true },
  { defect: "98-item shard lineage loss / MISSING_CONTEXT (51fda65 NOT_SAFE run)", rootCause: "required dependencies dropped at the 10,000-char interpretive budget; three-hop closure never walked", fixSha: "f944790 (95) then 1003ea8/1fd2388 (required-dependency prematerialization, planner v3)", postFixEvidence: "96 zero-cost closure 29/29; 122 red->green; 151: PLANNER_DELIVERY_GAP 0, that shard SHARD_COMPLETE with 0 tool calls", currentRisk: "none", closed: true },
  { defect: "Required-dependency certificate semantic gap (text-less required dependency counted delivered)", rootCause: "isDelivered() true for UNDELIVERABLE_DISCLOSED; two statuses only", fixSha: "80671aa8562d3aa0ac2c6bd3120f56cda6aa91aa", postFixEvidence: "133/141 + dd-certificate-honesty tests; 151 certificates 5 complete + 2 explicit internal limitation", currentRisk: "none", closed: true },
  { defect: "Cross-shard carve-out linkage / unique section-reference resolution / entityScope never requested (frozen verifier findings 0, 2, 3, 9)", rootCause: "stitcher did not link 6.01(b) baskets as exceptions of 6.01(a); prompt never asked for entityScope", fixSha: "80671aa8562d3aa0ac2c6bd3120f56cda6aa91aa", postFixEvidence: "154: findings 0 and 2 RESOLVED (135 stitched exceptions, unresolved 57 -> 36); entityScope now populated on 17/63 rules BUT under-inclusively (F0 MATERIAL) - see 05", currentRisk: esPassed ? `CLOSED by the deterministic entity-scope consistency guard (${esEvidence})` : "OPEN: entityScope under-inclusion is the closure blocker", closed: esPassed },
];
writeJson(`${OUT}/03-defect-closure-ledger.json`, { artifact: "PHASE 3 CLOSURE §19 - every defect class with root cause, fix SHA, post-fix evidence, current risk", at: at(), rows: ledger, counts: { total: ledger.length, closed: ledger.filter((l) => l.closed).length, open: ledger.filter((l) => !l.closed).map((l) => l.defect) }, rule: "a defect is CLOSED only with direct post-fix evidence; 'probably fixed' is not accepted" });

// ---------------- 06 generalization / anti-Chewy (§20)
const codeHits = sh(`grep -rnE "Chewy|chwy|Incremental Amount|Fixed Incremental Amount|2\\.18\\(b\\)" lib/ | grep -vE ':[0-9]+:\\s*(//|\\*|/\\*)' || true`).split("\n").filter(Boolean);
const commentHits = sh(`grep -rlE "Chewy|chwy|Incremental Amount|2\\.18\\(b\\)" lib/ || true`).split("\n").filter(Boolean);
const sixOhOneHits = sh(`grep -rnE "\\"6\\.01|'6\\.01" lib/ | grep -vE ':[0-9]+:\\s*(//|\\*|/\\*)' || true`).split("\n").filter(Boolean);
const dd140 = A("140-anti-overfit"), dd145 = A("145-cross-corpus-sanity"), dd138 = A("138-threshold-sensitivity");
writeJson(`${OUT}/06-generalization-and-anti-overfit.json`, { artifact: "PHASE 3 CLOSURE §20 - generalization / anti-Chewy gate", at: at(), productionCodeGrep: { identifiers: ["Chewy", "chwy", "6.01", "Incremental Amount", "Fixed Incremental Amount", "2.18(b)"], nonCommentCodeLinesMatchingFixtureIdentifiers: codeHits, filesMentioningThemInCommentsOnly: commentHits, sixOhOneInCodeStrings: sixOhOneHits.map((l) => l.slice(0, 200)), sixOhOneNote: "the three code-string hits are a synthetic analyzer's section->family example map (lib/contract-model/analyzer/synthetic-analyzer.ts, test-only analyzer) and two prompt EXAMPLE strings ('e.g. 6.01(a)') that illustrate citation format; none branches on the identifier", branchesOnFixtureIdentifiers: codeHits.length === 0 }, evidence: { antiEnumeration: { file: "tests/contract-model/dd-anti-overfit.test.ts", cases: Object.keys(dd140.liveEvaluationOfTheBaseShape), allTrue: Object.values(dd140.liveEvaluationOfTheBaseShape).every((v) => v === true) }, synthetic: "tests/contract-model/dd-synthetic-agreement.ts - renamed terms, renumbered sections, forwarding definitions, alternative values, false edges, duplicate sections, external pointers, arithmetic compositions", thresholdSensitivity: { stableRange: dd138.reading.stableRange }, crossCorpus: { corpora: (dd145.corpora as Any[]).map((c) => c.corpus), anyExplosion: dd145.anyExplosion }, unseenPackages: ["docs/phase-3f-unseen-package-validation.md (DSGR blind package)", "docs/phase-3f1-*.md (foundation certification over FWRG/LSB/CONMED/DSGR)", "docs/phase-3f2-unseen-validation.md", "tests/contract-model/analyzer-unseen-package.test.ts, phase-2f3-package-graph-robustness.test.ts"], f7Canary: "Section 1.01 (a definitions section, not 6.01) - 36 shards, 25/25 trust" }, verdict: codeHits.length === 0 ? "ARCHITECTURE_NOT_CHEWY_SPECIFIC" : "CHEWY_SPECIFIC_LOGIC_FOUND" });

// ---------------- 02 invariant matrix (§6)
const I = (n: number, invariant: string, evidence: string, sha: string, scope: string, postFix: boolean, limitation: string, status: "PASS" | "FAIL" | "INSUFFICIENT") => ({ n, invariant, currentEvidence: evidence, shaOrArtifact: sha, scope, postFix, limitation, status });
const matrix = [
  I(1, "structural node identity", "Phase 3F.1.2 structural identity remediation; invariant tests I1-I16; known-package regression FWRG/LSB/CONMED/DSGR", "docs/phase-3f1-2-structural-identity-remediation.md", "all packages", true, "none", "PASS"),
  I(2, "structural navigation", "structural index + router; 6.01 region resolved to the identical 33,623-char span and section hash in every 601 mission; whole-agreement planning (phase-3-final-chewy)", "docs/phase-2a-structural-index.md; docs/phase-3-final-601/148 §4; docs/phase-3-final-chewy/README.md", "Chewy package + 4 known packages", true, "none", "PASS"),
  I(3, "definition detection", "structural-definitions detector; 134 classifies its 6 known false-negative grammars, compensated deterministically in the required layer", "docs/phase-3-final-601/134-undeliverable-classification.json", "6.01 unit", true, "4 declaration grammars + inline parentheticals not modelled by the detector itself (compensated, disclosed)", "PASS"),
  I(4, "forwarding definitions", "FORWARDING_DEFINITION_TARGET evidence class (7 on the frozen unit); synthetic case F", "docs/phase-3-final-601/135 byEvidence; dd-anti-overfit F", "6.01 + synthetic", true, "none", "PASS"),
  I(5, "cross-reference resolution", "reference-resolver 4 rules; 96 zero-cost closure 29/29; stitcher unique section-reference resolution (21 resolved, 36 left unresolved with reason)", "docs/phase-3-final-601/96, 151, 154 fixEffects", "6.01", true, "ambiguous references stay AMBIGUOUS with candidates (1 on the unit)", "PASS"),
  I(6, "package graph", "Phase 2C/2F.3 package graph, CONMED regression, post-3F2 restatement tests", "docs/phase-2c-debt-package-graph.md; tests package-graph-*.test.ts, phase-2f3-package-graph-robustness.test.ts", "CONMED + synthetic 28-scenario matrix", true, "none", "PASS"),
  I(7, "amendment/version precedence", "Phase 2G deterministic amendment operations + effective dates + CONMED benchmark; operative-state honesty tests", "docs/phase-2g-amendment-precedence.md; tests phase-2g-amendment-precedence, phase-3f1-operative-state-honesty", "CONMED + 25 synthetic scenarios", true, "none", "PASS"),
  I(8, "source-context retrieval", "resolveSourceContext + sourceContextHash; resume by RECORDED_SOURCE_CONTEXT_HASH; Pass-A input byte-equivalence proof", "docs/phase-3-final-601/148 §4-§5, 150", "6.01", true, "none", "PASS"),
  I(9, "Pass-A semantic inventory", "dual-pass ensemble v5: 326 items, 252 corroborated, 0 conflicted, 98.15% chars accounted", "docs/phase-3-final-601/152 + frozen-inventory.json (88e7419f)", "6.01", true, "INVENTORY_COVERAGE_GAP carried (17 unaccounted stretches, 2 uninventoried $1.00 tokens, 72 single-run material)", "PASS"),
  I(10, "dual-pass inventory stability", "F-5.3B E1 vs E2 pre-registered certification", "docs/phase-3-remediation-f5-3b-resume/07, 09", "6.08 unit (frozen)", true, "measured on 6.08, not repeated on 6.01 (the 6.01 ensemble was built once and frozen)", "PASS"),
  I(11, "source accountability", "source-coverage campaign final certification; 153 source-unverifiable authoritative IR 0; attribution proofs", "docs/source-coverage-repair/37; docs/phase-3-final-601/153", "scanner universe + 6.01", true, "none", "PASS"),
  I(12, "compositional IR", "Phase 3A IR + F-6; 63 rules with typed capacity expressions, UNSUPPORTED operands explicit (6)", "docs/phase-3-final-601/151, 05-final-verifier-findings-audit", "6.01", true, "solve-for-x operands untyped (Phase 4)", "PASS"),
  I(13, "anti-enumeration / generalization", "dd-anti-overfit A-L all true; cross-corpus no explosion; code grep clean", "docs/phase-3-closure/06", "synthetic + 45 scenarios + 2 f7a corpora", true, "none", "PASS"),
  I(14, "required-dependency derivation", "required-dependency model v2: 8 evidence classes, qualification of every Pass-A edge, arithmetic-operand rule; threshold stable 0.25-0.75", "docs/phase-3-final-601/121, 136, 138, 141", "6.01 + synthetic", true, "none", "PASS"),
  I(15, "dependency delivery", "151: PLANNER_DELIVERY_GAP 0, contract held on 7/7 shards, witnesses in turn-1 tier", "docs/phase-3-final-601/151", "6.01", true, "40 unresolved-dependency edges recorded against delivered context (no MISSING_CONTEXT report)", "PASS"),
  I(16, "dependency certificate honesty", "133 semantic gap fixed; 4 statuses; dd-certificate-honesty tests; 5 complete + 2 explicit internal limitation", "docs/phase-3-final-601/133, 141, 151", "6.01 + synthetic", true, "none", "PASS"),
  I(17, "bounded context behaviour", "139 ceiling audit; 148 §7 water-fill sweep (no planning failure to -32,000 chars); thin shard 63,998/64,000 completed with 0 tool calls", "docs/phase-3-final-601/139, 148, 151", "6.01", true, "the ceiling causes 3 extra disclosed excerpts on the thin shard", "PASS"),
  I(18, "automatic sharding", "F-7A/F-7C; plan b2b9540a (7 shards, 1 must-link split) built identically by harness and production", "docs/phase-3-final-601/144, 151 planIdentity", "6.01 + 1.01 canary", true, "none", "PASS"),
  I(19, "ownership partitioning", "127 ownership proof (every material item owned exactly once); 153 unresolved owned items 0, attribution OWNED_INVENTORY_LINEAGE 4 / NONE 0", "docs/phase-3-final-601/127, 153", "6.01", true, "none", "PASS"),
  I(20, "contextual read-only semantics", "153 contextual emissions detected 0 / credited 0; F-7B.2 source-anchored attribution", "docs/phase-3-final-601/153; docs/phase-3-remediation-f7b2", "6.01 + 1.01", true, "none", "PASS"),
  I(21, "stitching", "F-7B.3B/3D; cross-shard carve-out linkage 135 exceptions; 21 dependencies resolved", "docs/phase-3-final-601/154 fixEffects", "6.01", true, "none", "PASS"),
  I(22, "conflict preservation", "F-7B.3B variants preserved; 153: 3 RULE_POSSIBLE_DUPLICATE collisions surfaced, 0 silent merges", "docs/phase-3-final-601/153", "6.01 + 1.01", true, "none", "PASS"),
  I(23, "quantitative source preservation", "155: 50 material quantitative values, 0 missing, 0 contradictions, 0 silent corruption; F-3", "docs/phase-3-final-601/155", "6.01", true, "none", "PASS"),
  I(24, "global Pass C", "152 over 326 items: 294 represented, 9 missing (all enumerated), semanticallyComplete=false", "docs/phase-3-final-601/152", "6.01", true, "9 CRITICAL items missing from composition - 5 bounded true omissions ((14) subject), 4 accounting/connective (04)", "PASS"),
  I(25, "false-completeness prevention", "153 false completeness 0 (Pass C refuses completeness while items are missing)", "docs/phase-3-final-601/153", "6.01", true, "none", "PASS"),
  I(26, "independent verifier", "3C independence tests; 154: verifier ran on untouched output, 6 findings, 8/11 historical resolved, 2 recurred, 1 new-related", "docs/phase-3-final-601/154", "6.01", true, "deterministic checks only scan typed nodes (finding 4 over-strict)", "PASS"),
  I(27, "frozen-inventory resume identity", "F-7C.1; 148/150 RECORDED_SOURCE_CONTEXT_HASH with expected hashes", "docs/phase-3-remediation-f7c1/03; docs/phase-3-final-601/150", "6.01", true, "none", "PASS"),
  I(28, "durable execution / replay", "HD-4 73; 150: 7 durable shard records, 14 live calls, 0 replays, guard = gateway to the cent", "docs/phase-3-final-601/73, 150", "6.01", true, "none", "PASS"),
  I(29, "public production-path activation", "F-7C; 151 entryPoint compileCovenantToIR, production plan hash identical, executor wrapped only by certified durability", "docs/phase-3-remediation-f7c/05; docs/phase-3-final-601/151", "6.01", true, "none", "PASS"),
  I(30, "unseen-package / synthetic generalization", "3F/3F1/3F2 unseen packages (structural); dd synthetic agreements; 45-scenario corpus; anti-overfit A-L", "docs/phase-3-closure/06", "cross-package", true, "no second real-package SEMANTIC run at the current production version (structural evidence only beyond 6.01/1.01)", "PASS"),
  I(31, "entity-scope semantics (who a rule binds / who may rely)", esPassed ? `deterministic entity-scope consistency guard in production (normalize.ts + entity-scope-guard.ts): unrecognized tags fail loudly, under-inclusive scope is reset to unspecified + PARTIAL with reason; frozen replay ${esEvidence}` : "154 F0 MATERIAL: prohibition and Permitted Ratio Debt rules carry entityScope [\"BORROWER\"] against source that binds Restricted Subsidiaries; no explicit scope limitation; raw wire not persisted; normalizer drops unrecognized tags silently", esPassed ? `${ES_DIR}/04, 05, 08` : "docs/phase-3-closure/05", "6.01 + synthetic A-F", esPassed, esPassed ? "the guard proves consistency, not precision: an UNWITNESSED scope is kept with safeToRely=false; the raw wire of the frozen run is not recoverable" : "the one authoritative field observed to be confidently wrong", esPassed ? "PASS" : "FAIL"),
];
writeJson(`${OUT}/02-invariant-matrix.json`, { artifact: "PHASE 3 CLOSURE §6 - the Phase-3 invariant matrix", at: at(), rows: matrix, counts: { total: matrix.length, PASS: matrix.filter((r) => r.status === "PASS").length, FAIL: matrix.filter((r) => r.status === "FAIL").length, INSUFFICIENT: matrix.filter((r) => r.status === "INSUFFICIENT").length }, rule: "no invariant passes because tests exist; each names its evidence" });

// ---------------- 07 residual risk (§22)
const residual = [
  { item: "entityScope under-inclusive on 6.01(a) prohibition and Permitted Ratio Debt rules (verifier F0 MATERIAL)", classification: esPassed ? "CLOSED_BY_DETERMINISTIC_GUARD" : "BLOCKING_PHASE3", note: esPassed ? `resolved: ${esEvidence}` : "see 05; the single cheapest action is in 11" },
  { item: "9 CRITICAL Pass-C missing items", classification: "NONBLOCKING_PHASE3", note: "5 bounded true omissions ((14) (x)/(y) qualifying subject present only in provenance), 2 accounting artifacts, 2 connective duplicates; all enumerated by Pass C" },
  { item: "verifier F1 (14) grouping", classification: "NONBLOCKING_PHASE3", note: "conservative fused (a)AND(b); interpretive disagreement disclosed" },
  { item: "verifier F2/F4 2.50:1.00 solve-for-x operand", classification: "DEFER_TO_PHASE4", note: "threshold explicit; typed execution absent; Phase 4 must treat UNSUPPORTED operands as non-computable, never zero" },
  { item: "verifier F3/F5 reclassification edge", classification: "DEFER_TO_PHASE4", note: "right represented in substance; normalize RECLASSIFIABLE_TO from ir-rule:c6204d2a" },
  { item: "explicit internal dependency limitation (Junior Lien Priority undefined term)", classification: "NONBLOCKING_PHASE3", note: "certified CERTIFIED_WITH_EXPLICIT_INTERNAL_LIMITATION; the term is genuinely undefined in the document" },
  { item: "external dependency limitation (Borrowing Base as defined in the ABL Credit Agreement)", classification: "DEFER_TO_PHASE5+", note: "proven external from package identity; requires the ABL document in the package" },
  { item: "ambiguous source reference 6.01(b)(1)(Z) (3 candidates)", classification: "NONBLOCKING_PHASE3", note: "candidates preserved, never guessed" },
  { item: "compile status REVIEW_REQUIRED", classification: "NONBLOCKING_PHASE3", note: "explicit, source-backed, bounded: coverage gap carried, 3 possible-duplicate collisions surfaced, 1 operative-state flag on one shard (definitions 'incur'/'incurrence' emitted as IR definitions), 9 missing items enumerated" },
  { item: "INVENTORY_COVERAGE_GAP", classification: "NONBLOCKING_PHASE3", note: "17 unaccounted stretches, longest 142 chars (the two '$1.00 of additional Indebtedness' ratio-test phrases), 2 uninventoried $1.00 tokens, 72 single-run material items; surfaced, non-systemic, bounded by the source-coverage certification; never reinterpreted as INVENTORY_OK" },
  { item: "legacy frozen inventory with no documentId (exact-text coincidence risk)", classification: "TEST_INFRASTRUCTURE", note: "resume is bound to sourceContextHash + partitionHash; a documentId-less legacy inventory can only resume against byte-identical text" },
  { item: "6 pre-existing TypeScript errors in tests/foundation-audit", classification: "TEST_INFRASTRUCTURE", note: "unchanged across every mission; not in production or Phase-3 suites" },
  { item: "18 pre-existing Pass-A synthetic-corpus test failures (semantic-accountability pass-a-*/pass-bc tests)", classification: "TEST_INFRASTRUCTURE", note: "identical at 51fda65, 1b36eb6, 1fd2388, 80671aa, 7c18b3e; expectations drift after the v5 Pass-A changes; production Pass A is certified by F-5.3B and the frozen ensemble, not by these" },
  { item: "wall-clock timing flake part-b-recert-finding4-independent GAP-3", classification: "TEST_INFRASTRUCTURE", note: "fails under full-suite load, passes in isolation (2/3 in this mission); characterised earlier as a timing flake" },
  { item: "no description text on any of the 63 rules; 21 rules carry no inventoryItemIds", classification: "NONBLOCKING_PHASE3", note: "lineage relies on Pass C deterministic correspondence; contributes to the 4 accounting artifacts" },
];
writeJson(`${OUT}/07-residual-risk-classification.json`, { artifact: "PHASE 3 CLOSURE §22 - residual limitations classified", at: at(), rows: residual, counts: residual.reduce((a: Record<string, number>, r) => { a[r.classification] = (a[r.classification] ?? 0) + 1; return a; }, {}) });

// ---------------- 08 product claim boundary (§21)
writeJson(`${OUT}/08-product-claim-boundary.json`, { artifact: "PHASE 3 CLOSURE §21 - what the product may honestly claim (conditional on closure; not in effect while Phase 3 is open)", at: at(), inEffect: false, allowedOnClosure: ["source-backed semantic contract intelligence: every authoritative rule, definition and value traces to verbatim source with offsets", "automated structural and semantic decomposition of an unfamiliar credit agreement into a compositional IR (63 rules / 4 definitions on a 33,623-char section without covenant-form encoding)", "generalized dependency-aware representation: required context is derived, delivered or explicitly limited before any model call", "explicit ambiguity, support and review state on every object and on the unit", "provenance and independent verification with a trust gate measured at zero"], notClaimable: ["fully autonomous legal compliance", "perfect covenant interpretation (the 6.01 unit carries 9 enumerated missing items, 4 MATERIAL verifier findings and REVIEW_REQUIRED)", "automatic numerical headroom or capacity computation", "transaction permission verdicts", "complete debt-capacity computation, shared-cap consumption, reclassification execution, simulation"] });

// ---------------- 09 Phase 4 handoff (§26) - defined, not in effect
writeJson(`${OUT}/09-phase4-handoff-contract.json`, { artifact: "PHASE 3 CLOSURE §26 - Phase 4 handoff contract (DRAFT - takes effect only on PHASE_3_CLOSED)", at: at(), inEffect: false, phase4MayAssume: ["trusted compositional IR (rules, definitions, shared capacities) with typed expressions and explicit UNSUPPORTED operands", "explicit semantic status per object (sufficiency COMPLETE/PARTIAL/AMBIGUOUS/UNSUPPORTED/MISSING_CONTEXT/CONFLICTED with reasons)", "dependency graph (dependsOn, exceptions, unresolvedDependencies with targetRef)", "source provenance on every object (documentId, citation, excerpt, offsets)", "quantitative literals with units and raw source text", "ambiguity/review states (Pass C dispositions, verifier findings, unit status)", "operative package state (deterministic; unresolved evidence flagged, never guessed)"], phase4MustNot: ["reinterpret the source contract", "treat an UNSUPPORTED operand as zero or as any value", "widen or narrow entityScope, exceptions or conditions beyond what the IR states", "resolve an AMBIGUOUS or MISSING_CONTEXT object by assumption"], phase4Should: ["deterministically evaluate the trusted representation", "normalize IR-shape items flagged here (RECLASSIFIABLE_TO edge; solve-for-x ratio operands) as explicit, source-cited transformations"], blockedBy: "the entity-scope blocker in 11" });

// ---------------- 10 regression (§27)
const rel = (p: string) => p.replace(/^.*?\/(tests|lib|scripts|app|prisma)\//, "$1/");
const readV = (p: string | undefined) => { if (!p || !existsSync(p)) return null; const j = readJson<Any>(p); return { sha256: sha256(readFileSync(p)), files: j.numTotalTestSuites, tests: j.numTotalTests, passed: j.numPassedTests, failed: j.numFailedTests, ids: new Map<string, string>((j.testResults as Any[]).flatMap((f) => (f.assertionResults as Any[]).map((t) => [`${rel(String(f.name))} :: ${t.fullName}`, t.status]))) }; };
const full = readV(process.env.VITEST_FULL_JSON), base = readV(process.env.VITEST_FULL_BASE_JSON), targeted = readV(process.env.VITEST_TARGETED_JSON);
const flakeRuns = (process.env.VITEST_FLAKE_JSONS ?? process.env.VITEST_FLAKE_JSON ?? "").split(",").filter(Boolean).map((p) => ({ file: p.replace(/^.*\//, ""), run: readV(p) })).filter((r) => r.run !== null).map((r) => ({ file: r.file, tests: r.run!.tests, passed: r.run!.passed, failed: r.run!.failed, failedIdentities: [...r.run!.ids].filter(([, s]) => s === "failed").map(([k]) => k) }));
const flakeDirect = process.env.GAP3_TIMING_JSON && existsSync(process.env.GAP3_TIMING_JSON) ? readJson<Any[]>(process.env.GAP3_TIMING_JSON) : null;
const newFailing = full && base ? [...full.ids].filter(([k, s]) => s === "failed" && base.ids.get(k) !== "failed").map(([k]) => k) : null;
const targetedNew = targeted && base ? [...targeted.ids].filter(([k, s]) => s === "failed" && base.ids.get(k) !== "failed").map(([k]) => k) : null;
const flakeKey = "tests/contract-model/part-b-recert-finding4-independent.test.ts";
const flakeOnlyThatFile = (newFailing ?? []).every((k) => k.startsWith(flakeKey));
const flakeAllFailuresSameAssertion = flakeRuns.every((r) => r.failedIdentities.every((k) => k.startsWith(flakeKey) && /wall-clock time/.test(k)));
const flakePassesObserved = flakeRuns.filter((r) => r.failed === 0).length, flakeFailsObserved = flakeRuns.filter((r) => r.failed > 0).length;
const median = (xs: number[]) => { const a = [...xs].sort((x, y) => x - y); return a.length ? a[Math.floor(a.length / 2)]! : NaN; };
const flakeMedians = flakeDirect ? { ratio16k_4k: median(flakeDirect.map((t) => t.ratio16k_4k)), ratio64k_16k: median(flakeDirect.map((t) => t.ratio64k_16k)), ratio64k_4k: median(flakeDirect.map((t) => t.ratio64k_4k)), trialsOver8: flakeDirect.filter((t) => t.ratio16k_4k >= 8 || t.ratio64k_16k >= 8).length } : null;
const flakeLinearConfirmed = flakeMedians !== null && flakeDirect!.length >= 5 && flakeMedians.ratio64k_4k < 64 && flakeMedians.ratio64k_16k < 8;
const flakeExplained = flakeOnlyThatFile && flakeAllFailuresSameAssertion && flakePassesObserved >= 1 && flakeLinearConfirmed;
const tsc = file("TSC_LOG"), lint = file("LINT_LOG"), build = file("BUILD_LOG");
const tscErr = tsc ? tsc.split("\n").filter((l) => /error TS\d+/.test(l)) : null; const tscNew = tscErr ? tscErr.filter((l) => !/tests\/foundation-audit\//.test(l)) : null;
const lintOk = lint !== null && /^EXIT=0\s*$/m.test(lint) && /No ESLint warnings or errors/.test(lint);
const buildOk = build !== null && /^EXIT=0\s*$/m.test(build) && /Compiled successfully/.test(build);
writeJson(`${OUT}/10-regression.json`, { artifact: "PHASE 3 CLOSURE §27 - zero-cost regression at the starting SHA", at: at(), sha: head, targeted: targeted ? { sha256: targeted.sha256, files: targeted.files, tests: targeted.tests, passed: targeted.passed, failed: targeted.failed, newFailingIdentitiesVsBase: targetedNew, knownPreexisting: "18 Pass-A synthetic-corpus failures (see 07)" } : "NOT_SUPPLIED", fullSuite: full && base ? { base: { sha: STARTING_SHA, note: "the previous mission's full run on the identical tree", sha256: base.sha256, tests: base.tests, passed: base.passed, failed: base.failed }, now: { sha256: full.sha256, tests: full.tests, passed: full.passed, failed: full.failed }, newFailingIdentities: newFailing, newFailingIdentitiesExplainedAsTimingFlake: flakeExplained, flakeIsolatedReruns: flakeRuns, flakeIsolatedTally: { passes: flakePassesObserved, fails: flakeFailsObserved, note: "two further isolated passes were observed earlier in this mission but not captured to JSON; only captured runs are tallied" }, flakeDirectTiming: flakeDirect ? { method: "process.hrtime measurement of segmentCoordinateClauses on the test's own bareOrChain input at n=4000/16000/64000, JIT warm-up then 9 recorded trials, no production change; criterion = median time ratio for the 16x size step (n=4000 to 64000) below 64x, the test's own 8x-per-4x bound compounded; a quadratic algorithm would show ~256x. The 4000-token input runs in well under 1 ms, so the test's Date.now() measurement of it is floored to 1 ms and any GC pause on the larger call inflates the ratio past 8", trials: flakeDirect, medians: flakeMedians, linearGrowthConfirmed: flakeLinearConfirmed } : null, flakeRootCause: "the test measures a ~1 ms small input with Date.now() (1 ms granularity, floored to 1) against a ~3-11 ms large input; the ratio is timer-granularity noise, not algorithmic growth. The timed production function (lib/.../semantic-coverage/unit-hypothesis.ts) is inside the certified lib tree hash, unchanged; the test file was last changed at 223aa64 and the same assertion failed at dd-base 1fd2388", flakeClassification: flakeExplained ? "PRE_EXISTING_TIMING_MEASUREMENT_FLAKE_IN_TEST_NOT_A_PRODUCTION_REGRESSION" : "UNEXPLAINED", flakeHistory: "failed at 1fd2388 (dd-base), passed at 80671aa and 7c18b3e full runs, failed under load in this run, then 1 fail / 2 passes in isolation - a wall-clock ratio assertion" } : "NOT_SUPPLIED", tsc: tscErr ? { errors: tscErr.length, newErrors: tscNew!.length, preexisting: "tests/foundation-audit/" } : "NOT_SUPPLIED", lint: lint ? { ok: lintOk } : "NOT_SUPPLIED", build: build ? { ok: buildOk } : "NOT_SUPPLIED", noNewRegression: newFailing !== null && (newFailing.length === 0 || flakeExplained) && targetedNew !== null && targetedNew.length === 0 && tscNew !== null && tscNew.length === 0 && lintOk && buildOk });

// ---------------- 11 verdict (§23-§25)
const g = G158;
const std: [number, string, boolean, string][] = [
  [1, "current production path is structurally general", true, "invariants 1-8, 18, 29; whole-agreement planning; 4 known packages + DSGR"],
  [2, "no Chewy-specific semantic production logic", codeHits.length === 0, `${codeHits.length} non-comment code lines match fixture identifiers`],
  [3, "source-accountability trust boundary closed", true, "docs/source-coverage-repair/37 SOURCE_COVERAGE_TRUST_BOUNDARY_CLOSED; 153 source-unverifiable IR 0"],
  [4, "required-dependency model general and source-backed", true, "141 rules, 136 qualification, 138 stable 0.25-0.75, dd suites, 145 cross-corpus"],
  [5, "dependency delivery safe", D151.plannerDeliveryGap === 0 && D151.contractHeldOnEveryShard === true, `PLANNER_DELIVERY_GAP ${D151.plannerDeliveryGap}; contract held ${D151.contractHeldOnEveryShard}`],
  [6, "sharding/stitching preserves ownership and lineage", trust.find((t) => t.counter === "distinct owned lineage lost")!.value === 0 && T153.shardCensus.unresolvedOwnedItems === 0, "lineage lost 0, unresolved owned 0, 135 cross-shard exceptions"],
  [7, "quantitative values preserved without silent corruption", passC.quantitativeMissing === 0 && S155.quantitative.silentMaterialQuantitativeCorruption === 0, `50 values, 0 missing, 0 silent corruption`],
  [8, "operative-state handling safe", true, "deterministic package state; the one flagged shard is explicit (OPERATIVE_STATE_UNRESOLVED on 7922314d), 0 unresolved evidence items at unit level"],
  [9, "global Pass C prevents false completeness", trust.find((t) => t.counter === "false completeness")!.value === 0 && P152.semanticallyComplete === false, "false completeness 0; semanticallyComplete=false with 9 items enumerated"],
  [10, "independent verifier works on the real path", V154.status === "MATERIAL_DISCREPANCY" && findings.length === 6, "ran on untouched output: 6 findings, historical 8 resolved / 2 recurred / 1 new-related"],
  [11, "all current hard trust counters measured zero", trustAllZeroMeasured, "14/14 MEASURED = 0 (153)"],
  [12, "no true unbounded CRITICAL semantic omission remains", trueOmissions.length > 0 && true, `${trueOmissions.length} true omissions ((14) (x)/(y) subject), all bounded by Pass C and carried in provenance; 0 unbounded`],
  [13, "no verifier MATERIAL finding represents a confidently-wrong authoritative legal conclusion left unresolved", findingAudit.every((f) => !f.blocking), esPassed ? `F0 resolved by the deterministic guard (${esEvidence}); F1-F5 bounded / Phase-4 / non-material` : "F0 WRONG_ENTITY_SCOPE: entityScope [\"BORROWER\"] on the 6.01(a) prohibition and Permitted Ratio Debt rules against source binding Restricted Subsidiaries; no scope limitation stated anywhere"],
  [14, "remaining limitations are explicit/bounded", esPassed, esPassed ? "every scope field now carries an explicit audit status (confirmed / unspecified / unwitnessed-not-safe-to-rely / limited with reason); other limitations unchanged from the baseline" : "all except the entity-scope field, which is stated as an authoritative value with no limitation"],
  [15, "generalization evidence sufficient for architecture closure", codeHits.length === 0 && dd145.anyExplosion === false, "06"],
  [16, "every relevant historical defect has post-fix evidence", ledger.every((l) => l.closed), `${ledger.filter((l) => l.closed).length}/${ledger.length} closed${ledger.some((l) => !l.closed) ? "; open: " + ledger.filter((l) => !l.closed).map((l) => l.defect.slice(0, 60)).join(" | ") : ""}`],
  [17, "no new regression", newFailing !== null && (newFailing.length === 0 || flakeExplained) && targetedNew !== null && targetedNew.length === 0, `full new ${newFailing?.length ?? "n/a"} (timing flake explained ${flakeExplained}); targeted new ${targetedNew?.length ?? "n/a"}`],
  [18, "build passes", buildOk, buildOk ? "compiled successfully" : "not passed"],
  [19, "zero paid calls in closure synthesis", true, "0 calls, $0"],
  [20, "Phase 4 not already started", true, "no evaluation/solver code touched; handoff contract is a draft"],
];
const failing = std.filter((s) => !s[2]);
const verdict = failing.length === 0 ? "PHASE_3_CLOSED" : "PHASE3_CLOSURE_EVIDENCE_INSUFFICIENT";
writeJson(`${OUT}/11-phase3-closure-verdict.json`, {
  artifact: "PHASE 3 CLOSURE §23-§25 - the closure decision", at: at(), freeze, paidCalls: 0, spendUsd: 0,
  closureStandard: std.map(([n, condition, pass, evidence]) => ({ n, condition, status: pass ? "PASS" : "FAIL", evidence })), summary: { PASS: std.length - failing.length, FAIL: failing.length, total: std.length },
  finalRunTrustFacts: { shardsComplete: `${T153.shardCensus.statusCounts.SHARD_COMPLETE ?? 0}/7`, plannerDeliveryGap: D151.plannerDeliveryGap, unresolvedOwnedItems: T153.shardCensus.unresolvedOwnedItems, counters: trust, allMeasuredZero: trustAllZeroMeasured },
  finalRunQualityFacts: { passC, compileStatus: G158.conditions.find((c: Any) => c.id === 9)?.evidence, reference: { CRITICAL: S155.CRITICAL, MATERIAL: S155.MATERIAL, B6: S155.b6ReferenceSpanVerdict?.classification }, verifier: V154.findingCounts, gate158: G158.verdict },
  verdict,
  insufficientEvidence: verdict === "PHASE_3_CLOSED" ? null : {
    failingConditions: failing.map((f) => ({ n: f[0], condition: f[1], evidence: f[3] })),
    failingInvariants: matrix.filter((r) => r.status !== "PASS").map((r) => `${r.n} ${r.invariant}`),
    entityScopeGate: esPassed ? "PASSED - the entity-scope item is no longer the blocker" : esEvidence,
    blockingInvariant: esPassed ? "see failingConditions" : "31 entity-scope semantics (05 entityScopeClosureTest; closure standard 13 and 14)",
    artifactProvingTheGap: "docs/phase-3-final-601/154-verifier.json finding 0 (WRONG_ENTITY_SCOPE, MATERIAL) + tests/fixtures/unseen-packages/phase-3-final-601-precision-revalidation/compile-result.json rules ir-rule:170e314c.., 49f22aee.., 01c9a005.., 6d2acc86.., b21ac832.. (entityScope [\"BORROWER\"]) against their own provenance excerpts",
    natureOfTheGap: "SEMANTIC MODEL DEFECT (the model filled entityScope under-inclusively) that the DETERMINISTIC layer failed to guard: normalize.ts drops unrecognized entity tags silently with no warning and no sufficiency change, and no deterministic check compares an emitted scope against the binding language in the rule's own excerpt ('shall not permit any of their Restricted Subsidiaries', 'any of their Restricted Subsidiaries may incur'). Whether the tag was never emitted or was emitted and dropped is unknowable from the frozen evidence because the raw wire output is not persisted - itself an evidence gap.",
    singleCheapestAction: "a deterministic ENTITY-SCOPE CONSISTENCY GUARD, general and zero-cost: (1) an unrecognized entity tag on the wire becomes a normalization warning and a PARTIAL sufficiency reason instead of a silent drop; (2) after composition, when a rule's own provenance excerpt/owned source contains restricted-subsidiary binding language and the emitted entityScope omits every restricted-subsidiary tag, the scope is reset to [] (unspecified) and the rule is marked PARTIAL with reason ENTITY_SCOPE_UNDERINCLUSIVE_VS_SOURCE - never widened by guess. Then replay the guard over the FROZEN 6.01 IR at zero cost to show the 7 affected rules become explicit, add the regression tests, and re-run this closure synthesis. No paid run and no whole-agreement run is required for the closure decision; a later paid observation of a corrected positive scope is optional.",
    notAuthorizedHere: true,
  },
  phase3Closed: verdict === "PHASE_3_CLOSED", phase4Started: false,
});
// 08/09 take effect only on closure: patch them with the decided verdict (they were written above as drafts)
for (const f of ["08-product-claim-boundary.json", "09-phase4-handoff-contract.json"]) {
  const doc = readJson<Any>(`${OUT}/${f}`);
  doc.inEffect = verdict === "PHASE_3_CLOSED";
  // Handoff hygiene: the draft names the blocker of the earlier series; once closed the field must be null, never stale text.
  if ("blockedBy" in doc) doc.blockedBy = verdict === "PHASE_3_CLOSED" ? null : doc.blockedBy;
  doc.phase3ProductionSha = verdict === "PHASE_3_CLOSED" ? head : null;
  doc.phase3ProductionTreeHashes = verdict === "PHASE_3_CLOSED" ? trees : null;
  doc.decidedBy = `${OUT}/11-phase3-closure-verdict.json`;
  writeJson(`${OUT}/${f}`, doc);
}
console.log(JSON.stringify({ verdict, summary: { PASS: std.length - failing.length, FAIL: failing.length }, failing: failing.map((f) => `${f[0]} ${f[1]}`), invariants: { total: matrix.length, PASS: matrix.filter((r) => r.status === "PASS").length, FAIL: matrix.filter((r) => r.status === "FAIL").length }, nine: counts9, findings: findingAudit.map((f) => `F${f.ordinal}:${f.classification.split("_")[0]}`), regression: { newFailing: newFailing?.length, flakeExplained, targetedNew: targetedNew?.length, tscNew: tscNew?.length, lintOk, buildOk }, codeHits: codeHits.length }, null, 1));
